@startuml
title Warm house Payment Service Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(WarmHouseSystem, "Warm house payment system") {
  Container(WebApp, "Payment Service", "Go", "Handles payment request")
  Container(Database, "Database", "PostgreSQL")
}

Container(WebApp, "Web Application", "Go") {
  Component(PaymentController, "PaymentController", "Payment handler")
  Component(ServiceLayer, "Service Layer", "Business logic")
}

Rel(PaymentController,ServiceLayer,"Calls business logic")
Rel(ServiceLayer,Database, "Reads/Writes payment data")
@enduml