@startuml
title Warm house Video Surveillance Service Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(WarmHouseSystem, "Warm house video surveillance System") {
  Container(WebApp, "Video surveillance Service", "Go", "Handles video surveillance request")
  Container(Database, "Database", "PostgreSQL")
}

Container(WebApp, "Web Application", "Go") {
  Component(VideoSurveillanceController, "VideoSurveillanceController", "Video surveillance handler")
  Component(ServiceLayer, "Service Layer", "Business logic")
}

Rel(VideoSurveillanceController,ServiceLayer,"Calls business logic")
Rel(ServiceLayer,Database, "Reads/Writes video surveillance data")
@enduml