@startuml
title Warm house Light Service Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(WarmHouseSystem, "Warm house light System") {
  Container(WebApp, "Light Service", "Go", "Handles light sensor request")
  Container(Database, "Database", "PostgreSQL")
}

Container(WebApp, "Web Application", "Go") {
  Component(LightController, "LightController", "Light handler")
  Component(ServiceLayer, "Service Layer", "Business logic")
}

Rel(LightController,ServiceLayer,"Calls business logic")
Rel(ServiceLayer,Database, "Reads/Writes light sensor data")
@enduml